/**
 * Shared request/query schemas live in @wetestcase/dto.
 * This barrel keeps existing `@/lib/validations` imports working.
 */
export {
  roleSchema,
  executionStatusSchema,
  testTypeSchema,
  prioritySchema,
  projectStatusSchema,
  loginSchema,
  registerSchema,
  profileSchema,
  changePasswordSchema,
  projectSchema,
  projectUpdateSchema,
  moduleSchema,
  testCaseSchema,
  testCaseBulkDeleteSchema,
  executionSchema,
  executionEditSchema,
  commentSchema,
  fixStatusSchema,
  userCreateSchema,
  userUpdateSchema,
  testCaseQuerySchema,
  type LoginInput,
  type RegisterInput,
  type ProfileInput,
  type ChangePasswordInput,
  type ProjectInput,
  type ProjectOutput,
  type ModuleInput,
  type TestCaseInput,
  type ExecutionInput,
  type ExecutionEditInput,
  type CommentInput,
  type FixStatusInput,
  type UserCreateInput,
  type UserUpdateInput,
  type TestCaseQuery,
} from "@wetestcase/dto";
