#!/usr/bin/env bash
# Create a STABLE Cloudflare Tunnel hostname (survives app redeploy).
#
# Free trycloudflare.com URLs CANNOT stay the same — Cloudflare issues a new
# random host every time that process starts. A *named* tunnel + DNS hostname
# stays fixed forever and is independent of ./deploy/scripts/deploy.sh.
#
# Requirements:
#   - cloudflared installed (brew install cloudflared)
#   - Free Cloudflare account
#   - A domain added to Cloudflare (any domain; free plan is fine).
#     Without a domain, Cloudflare will not give a permanent public hostname.
#
# Usage:
#   ./deploy/scripts/setup-stable-cloudflare-tunnel.sh app.yourdomain.com
#
# One-time setup. After that:
#   - Redeploy app:  ./deploy/scripts/deploy.sh   (tunnel keeps running)
#   - Public URL:    https://app.yourdomain.com   (never changes)
set -euo pipefail

ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/../.." && pwd)"
cd "$ROOT"

HOSTNAME_ARG="${1:-}"
TUNNEL_NAME="${TUNNEL_NAME:-wetestcase}"
CF_DIR="${ROOT}/deploy/cloudflared"
ORIGIN="http://127.0.0.1:3000"

usage() {
  cat <<'EOF'
Usage:
  ./deploy/scripts/setup-stable-cloudflare-tunnel.sh <public-hostname>

Example:
  ./deploy/scripts/setup-stable-cloudflare-tunnel.sh cases.example.com

Steps this script runs (once):
  1. cloudflared tunnel login
  2. cloudflared tunnel create wetestcase  (or reuse if exists)
  3. Write deploy/cloudflared/config.yml  (points at http://127.0.0.1:3000)
  4. cloudflared tunnel route dns wetestcase <hostname>
  5. Install macOS LaunchDaemon so the tunnel restarts on reboot
  6. Write deploy/public-url.env with the stable HTTPS URL

Then set in .env.production and REBUILD once:
  BETTER_AUTH_URL=https://cases.example.com
  NEXT_PUBLIC_APP_URL=https://cases.example.com
  ./deploy/scripts/deploy.sh
EOF
}

if [[ -z "$HOSTNAME_ARG" || "$HOSTNAME_ARG" == "-h" || "$HOSTNAME_ARG" == "--help" ]]; then
  usage
  exit 0
fi

# Strip scheme/trailing slash if user pastes a full URL
PUBLIC_HOST="$(echo "$HOSTNAME_ARG" | sed -E 's#^https?://##; s#/.*##')"
PUBLIC_URL="https://${PUBLIC_HOST}"

if ! command -v cloudflared >/dev/null 2>&1; then
  echo "Install cloudflared first: brew install cloudflared" >&2
  exit 1
fi

mkdir -p "$CF_DIR"

echo "==> Login to Cloudflare (browser may open)"
cloudflared tunnel login

# Create tunnel if missing
EXISTING_ID="$(cloudflared tunnel list 2>/dev/null | awk -v n="$TUNNEL_NAME" '$2==n {print $1; exit}')" || true
if [[ -n "${EXISTING_ID:-}" ]]; then
  TUNNEL_ID="$EXISTING_ID"
  echo "==> Reusing existing tunnel '${TUNNEL_NAME}' (${TUNNEL_ID})"
else
  echo "==> Creating tunnel '${TUNNEL_NAME}'"
  CREATE_OUT="$(cloudflared tunnel create "$TUNNEL_NAME" 2>&1)"
  echo "$CREATE_OUT"
  TUNNEL_ID="$(echo "$CREATE_OUT" | grep -Eo '[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}' | head -1 || true)"
  if [[ -z "${TUNNEL_ID:-}" ]]; then
    TUNNEL_ID="$(cloudflared tunnel list 2>/dev/null | awk -v n="$TUNNEL_NAME" '$2==n {print $1; exit}')"
  fi
fi

if [[ -z "${TUNNEL_ID:-}" ]]; then
  echo "Could not determine tunnel UUID. Run: cloudflared tunnel list" >&2
  exit 1
fi

# Credentials: cloudflared usually stores under ~/.cloudflared/<UUID>.json
SRC_CREDS="${HOME}/.cloudflared/${TUNNEL_ID}.json"
DST_CREDS="${CF_DIR}/${TUNNEL_ID}.json"
if [[ ! -f "$SRC_CREDS" ]]; then
  # sometimes under /etc or already in project
  if [[ -f "$DST_CREDS" ]]; then
    SRC_CREDS="$DST_CREDS"
  else
    echo "Missing credentials file: ${SRC_CREDS}" >&2
    echo "Run: cloudflared tunnel create ${TUNNEL_NAME}" >&2
    exit 1
  fi
fi
cp -f "$SRC_CREDS" "$DST_CREDS"
chmod 600 "$DST_CREDS"

# Host LaunchDaemon config → always 127.0.0.1:3000 (survives image rebuilds)
cat > "${CF_DIR}/config.yml" <<EOF
# Generated by setup-stable-cloudflare-tunnel.sh — do not commit credentials.
# Named tunnel: public hostname stays the same across app redeploys.
tunnel: ${TUNNEL_ID}
credentials-file: ${DST_CREDS}

ingress:
  - hostname: ${PUBLIC_HOST}
    service: ${ORIGIN}
    originRequest:
      connectTimeout: 30s
  - service: http_status:404
EOF

echo "==> DNS route ${PUBLIC_HOST} → tunnel ${TUNNEL_NAME}"
cloudflared tunnel route dns "$TUNNEL_NAME" "$PUBLIC_HOST" || {
  echo "DNS route failed (hostname may already be routed). Check Cloudflare DNS for a CNAME to ${TUNNEL_ID}.cfargotunnel.com" >&2
}

# Persist stable public URL for scripts
cat > "${ROOT}/deploy/public-url.env" <<EOF
# Written by setup-stable-cloudflare-tunnel.sh — stable Cloudflare public URL.
# This does NOT change when you re-run ./deploy/scripts/deploy.sh
PUBLIC_APP_HOST=${PUBLIC_HOST}
PUBLIC_APP_URL=${PUBLIC_URL}
EOF

echo "==> Installing LaunchDaemon so the tunnel keeps running (and same URL) after reboot"
if [[ "$(id -u)" -ne 0 ]]; then
  sudo "${ROOT}/deploy/scripts/install-tunnel-launchd.sh"
else
  "${ROOT}/deploy/scripts/install-tunnel-launchd.sh"
fi

echo
cat <<EOF
================================================================
  STABLE Cloudflare URL ready
================================================================
  Public:  ${PUBLIC_URL}
  Origin:  ${ORIGIN}  (local app on this Mac)

  Redeploy the app anytime — URL stays the same:
    ./deploy/scripts/deploy.sh

  IMPORTANT — set auth hostnames and rebuild ONCE:
    In .env.production:
      BETTER_AUTH_URL=${PUBLIC_URL}
      NEXT_PUBLIC_APP_URL=${PUBLIC_URL}
    Then:
      ./deploy/scripts/deploy.sh

  Files (gitignored credentials):
    ${CF_DIR}/config.yml
    ${DST_CREDS}
    ${ROOT}/deploy/public-url.env

  Do NOT use run-free-tunnel.sh for production anymore
  (that always gets a new random trycloudflare.com host).
================================================================
EOF
